#!/usr/bin/python3

import math
import sys

def factorize_file(file):
    with open(file, 'r') as f:
        for line in f:
            num = int(line.strip())
            factors = factorize(num)
            for p, q in factors:
                print(f"{num}={p}*{q}")

def factorize(num):
    factors = 
    for i in range(2, int(math.sqrt(num)) + 1):
        if num % i == 0:
            factors.append((i, num // i))
    return factors

if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        exit(1)
    factorize_file(sys.argv[1]
