#!/usr/bin/python3

import sys

def factorize(number):
    factors = 
    
    for i in range(2, int(number**0.5) + 1):
        while number % i == 0:
            factors.append(i)
            number = number // i
    
    if number > 1:
        factors.append(number)
    
    return factors


def main():
    if len(sys.argv) != 2:
        print("Usage: factors <file>")
        return
    
    input_file = sys.argv
    
    with open(input_file, "r") as file:
        numbers = file.readlines()
    
    for number in numbers:
        number = int(number.strip())
        factors = factorize(number)
        
        result = f"{number}={int(number/factors[}*{factors}"
        print(result)


if __name__ == "__main__":
    main()
