#!/usr/bin/python3

import sys
import random
import time

import sys


def is_prime(number):
    if number <= 1:
        return False
    if number <= 3:
        return True
    if number % 2 == 0 or number % 3 == 0:
        return False
    
    i = 5
    while i * i <= number:
        if number % i == 0 or number % (i + 2) == 0:
            return False
        i += 6
    
    return True


def factorize(number):
    for i in range(2, number):
        if number % i == 0:
            if is_prime(i) and is_prime(number // i):
                return i, number // i


def main():
    if len(sys.argv) != 2:
        print("Usage: rsa <file>")
        return
    
    input_file = sys.argv
    
    with open(input_file, "r") as file:
        number = int(file.readline().strip())
    
    p, q = factorize(number)
    
    result = f"{number}={p}*{q}"
    print(result)


if __name__ == "__main__":
    main()
